@Lms.Course.Api_HostAddress = https://webapi-shiko-lms.azurewebsites.net

GET {{Lms.Course.Api_HostAddress}}/api/Courses
Accept: application/json

###

### Get popular courses
GET {{Lms.Course.Api_HostAddress}}/api/Courses/popular
Accept: application/json

### Get course by slug
GET {{Lms.Course.Api_HostAddress}}/api/Courses/digital-marketing
Accept: application/json