// <auto-generated />
using Lms.Course.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.Course.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260521102811_AddCourseDescription")]
    partial class AddCourseDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lms.Course.Domain.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseImage = "/images/courses/art-image.svg",
                            Duration = "10 hr 30 min",
                            InstructorImage = "/images/courses/samantha.svg",
                            InstructorName = "Samantha William",
                            LessonsCount = 15,
                            Rating = 4.9m,
                            Slug = "artificial-intelligence",
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            CourseImage = "/images/courses/data-image.svg",
                            Duration = "15 hr 20 min",
                            InstructorImage = "/images/courses/Karen.svg",
                            InstructorName = "Karen Hope",
                            LessonsCount = 25,
                            Rating = 4.7m,
                            Slug = "data-science-analytics",
                            Title = "Data Science & Analytics"
                        },
                        new
                        {
                            Id = 3,
                            CourseImage = "/images/courses/digital-image.svg",
                            Duration = "20 hr 40 min",
                            InstructorImage = "/images/courses/Jack.svg",
                            InstructorName = "Jack Sally",
                            LessonsCount = 5,
                            Rating = 4.8m,
                            Slug = "digital-marketing",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CourseImage = "/images/courses/ux-image.svg",
                            Duration = "25 hr 10 min",
                            InstructorImage = "/images/courses/Johnny.svg",
                            InstructorName = "Johnny Ahmed",
                            LessonsCount = 34,
                            Rating = 4.9m,
                            Slug = "ui-ux-design-for-beginner",
                            Title = "UI/UX Design for Beginner"
                        },
                        new
                        {
                            Id = 5,
                            CourseImage = "/images/courses/fullstack-image.svg",
                            Duration = "30 hr 50 min",
                            InstructorImage = "/images/courses/Hasan.svg",
                            InstructorName = "Hasan Smith",
                            LessonsCount = 30,
                            Rating = 4.7m,
                            Slug = "fullstack-developer",
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = 6,
                            CourseImage = "/images/courses/sketch-image.svg",
                            Duration = "12 hr 15 min",
                            InstructorImage = "/images/courses/Jasmin.svg",
                            InstructorName = "Jasmin Lila",
                            LessonsCount = 16,
                            Rating = 4.5m,
                            Slug = "sketch-for-designer",
                            Title = "Sketch for Designer"
                        },
                        new
                        {
                            Id = 7,
                            CourseImage = "/images/courses/art-image.svg",
                            Duration = "26 hr 15 min",
                            InstructorImage = "/images/courses/Jack.svg",
                            InstructorName = "Jack Sally",
                            LessonsCount = 24,
                            Rating = 4.5m,
                            Slug = "network-security",
                            Title = "Network Security"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
