// <auto-generated />
using Lms.Course.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lms.Course.Infrastructure.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260524142334_SeedCourseOverviews")]
    partial class SeedCourseOverviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lms.Course.Domain.Entities.CourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseImage = "/images/courses/art-image.svg",
                            Duration = "10 hr 30 min",
                            InstructorImage = "/images/courses/samantha.svg",
                            InstructorName = "Samantha William",
                            LessonsCount = 15,
                            Rating = 4.9m,
                            Slug = "artificial-intelligence",
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            CourseImage = "/images/courses/data-image.svg",
                            Duration = "15 hr 20 min",
                            InstructorImage = "/images/courses/Karen.svg",
                            InstructorName = "Karen Hope",
                            LessonsCount = 25,
                            Rating = 4.7m,
                            Slug = "data-science-analytics",
                            Title = "Data Science & Analytics"
                        },
                        new
                        {
                            Id = 3,
                            CourseImage = "/images/courses/digital-image.svg",
                            Duration = "20 hr 40 min",
                            InstructorImage = "/images/courses/Jack.svg",
                            InstructorName = "Jack Sally",
                            LessonsCount = 5,
                            Rating = 4.8m,
                            Slug = "digital-marketing",
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = 4,
                            CourseImage = "/images/courses/ux-image.svg",
                            Duration = "25 hr 10 min",
                            InstructorImage = "/images/courses/Johnny.svg",
                            InstructorName = "Johnny Ahmed",
                            LessonsCount = 34,
                            Rating = 4.9m,
                            Slug = "ui-ux-design-for-beginner",
                            Title = "UI/UX Design for Beginner"
                        },
                        new
                        {
                            Id = 5,
                            CourseImage = "/images/courses/fullstack-image.svg",
                            Duration = "30 hr 50 min",
                            InstructorImage = "/images/courses/Hasan.svg",
                            InstructorName = "Hasan Smith",
                            LessonsCount = 30,
                            Rating = 4.7m,
                            Slug = "fullstack-developer",
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = 6,
                            CourseImage = "/images/courses/sketch-image.svg",
                            Duration = "12 hr 15 min",
                            InstructorImage = "/images/courses/Jasmin.svg",
                            InstructorName = "Jasmin Lila",
                            LessonsCount = 16,
                            Rating = 4.5m,
                            Slug = "sketch-for-designer",
                            Title = "Sketch for Designer"
                        },
                        new
                        {
                            Id = 7,
                            CourseImage = "/images/courses/art-image.svg",
                            Duration = "26 hr 15 min",
                            InstructorImage = "/images/courses/Jack.svg",
                            InstructorName = "Jack Sally",
                            LessonsCount = 24,
                            Rating = 4.5m,
                            Slug = "network-security",
                            Title = "Network Security"
                        });
                });

            modelBuilder.Entity("Lms.Course.Domain.Entities.CourseOverviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPoints")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CourseOverviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 3,
                            Description = "The class is marketing to help you master the foundation of digital marketing. Through practical lessons and real world case studies. You'll learn how to solve - problem creatively and build impactful solutions.\r\nThis course is designed to help you build a strong understanding of digital marketing from the ground up. Through practical lessons, hands-on exercises, and real-world case studies, you’ll learn how modern brands attract, engage, and convert audiences online.",
                            DetailImage = "/images/courses/course-overview-digital.svg",
                            KeyPoints = "Set your marketing goals;Identify your target audience;Choose the right platform;Create compelling content;Launch and monitor your campaign;Pinpoint specific demographics and interests;Often lower cost than traditional advertising;Track performance in real-time"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Description = "Learn the fundamentals of artificial intelligence and machine learning through practical projects and real-world examples. This course introduces modern AI concepts and helps you understand how intelligent systems are built.",
                            KeyPoints = "Understand AI basics;Learn machine learning concepts;Work with real-world examples;Explore neural networks;Analyze data patterns;Build simple AI solutions;Understand automation systems;Learn ethical AI principles"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 2,
                            Description = "Learn how to collect, analyze, and visualize data using modern tools and techniques. This course helps you understand how businesses use data to make informed decisions.",
                            KeyPoints = "Understand data analysis;Work with datasets;Visualize information clearly;Learn basic statistics;Identify trends and patterns;Use analytical thinking;Create data reports;Understand business insights"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 4,
                            Description = "Discover the basics of user interface and user experience design. Learn how to create intuitive and visually appealing digital experiences for modern users.",
                            KeyPoints = "Understand user experience basics;Design clean interfaces;Learn wireframing techniques;Create user-friendly layouts;Improve accessibility;Work with design tools;Understand user behavior;Build responsive designs"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 5,
                            Description = "Learn both frontend and backend development to build complete web applications. This course covers modern technologies used in fullstack development.",
                            KeyPoints = "Build responsive frontend interfaces;Understand backend development;Work with APIs;Manage databases;Handle authentication systems;Use modern frameworks;Deploy web applications;Understand fullstack architecture"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 6,
                            Description = "Learn how to use Sketch for modern digital design projects. This course focuses on creating professional layouts, components, and design systems.",
                            KeyPoints = "Use Sketch tools effectively;Create reusable components;Design modern layouts;Work with typography;Build design systems;Organize design files;Collaborate with teams;Improve workflow efficiency"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 7,
                            Description = "Learn the fundamentals of network security and how to protect systems from cyber threats. This course introduces key security concepts used in modern IT environments.",
                            KeyPoints = "Understand cybersecurity basics;Identify security threats;Protect network systems;Learn encryption concepts;Manage secure connections;Understand firewalls;Prevent common attacks;Improve system security"
                        });
                });

            modelBuilder.Entity("Lms.Course.Domain.Entities.CourseOverviewEntity", b =>
                {
                    b.HasOne("Lms.Course.Domain.Entities.CourseEntity", "Course")
                        .WithOne("CourseOverview")
                        .HasForeignKey("Lms.Course.Domain.Entities.CourseOverviewEntity", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Lms.Course.Domain.Entities.CourseEntity", b =>
                {
                    b.Navigation("CourseOverview");
                });
#pragma warning restore 612, 618
        }
    }
}
